### ISSUE TITLE
Package not working

### ISSUE THREAD

**Issue by bmuenzenmeyer** [target/markdown-inject#16]
Paul noticed that the [1.0.0 publication](https://unpkg.com/browse/markdown-inject@1.0.0/) was not clean, missing all `dist` folders.

https://github.com/target/markdown-inject/commit/9089d856b4e956a8e59478cd73439a31a5c22e8d removed `build` from `prepare` - which is run during `publish` and `install` IIRC. We should either add it in or implement `prepublish`

I tried publishing a fix but do not have permissions in npm.

**Comment by bmuenzenmeyer** [comment]
resolved

**Comment by 10hendersonm** [comment]
This definitely throws some weight behind the need to wrap up https://github.com/target/markdown-inject/issues/1
