### ISSUE TITLE
Non-publish pipeline 

### ISSUE THREAD

**Issue by 10hendersonm** [target/markdown-inject#59]
Some changes that don't impact the emitted bundle (like #50, or other pipeline work) still create a release to `npm` which represents unnecessary change to users who habitually upgrade. 

A label-based `skip-release` path for PRs would mitigate this.

**Comment by bmuenzenmeyer** [comment]
@10hendersonm I wonder if we could experiment with a tool like changesets, to train up on a new thing

**Comment by bmuenzenmeyer** [comment]
https://github.com/target/markdown-inject/blob/main/scripts/release.mjs#L37
